name: Release

on:
  release:
    types: [published]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: node --version
      - run: npm --version
      - run: npm test
      - run: npm pack --dry-run
      - run: npm publish --provenance --access public
